### ISSUE TITLE
租户视图添加集群超时和重传默认参数不合理

### ISSUE THREAD

**Issue by haoxuebing** [bfenetworks/dashboard#5]
![image](https://user-images.githubusercontent.com/17307283/140503206-b04a43ad-8b2a-45c1-acda-869ee7adc632.png)

这俩参数太小了，操作这一步的时候很容易会把这忽视

在 bfe 中会报错 :
CONNECT_BACKEND,ConnectError: dial tcp xx.xx.xx.xx:80: i/o timeout, xx.xx.xx.xx:80

**Comment by clarinette9** [comment]
Thanks you . We are working on this.  Will fix it. Also document of bfe will be updated.

**Comment by clarinette9** [comment]
文档已更新 Document updated:  https://www.bfe-networks.net/zh_cn/configuration/server_data_conf/cluster_conf.data/ 
Fix in Dashboard will be come later .   Dashboard上默认值的修改会在之后完成
